#!/bin/bash

## Information
##
## openssl コマンドを使用して暗号化された文字列を復号します.
## 
## [openssl オプション]
## -aes-128-cbc：AES暗号、128ビット、CBCモード
## -d：復号
## -base64：入力をBase64で扱う。
## -pass pass:cipher：パスワードフレーズとしてcipherを使用
##

function usage(){
echo "usage : $(basename $0) encrypted_string"
}

str=$1
if [[ -z ${str} ]] ;then
  usage
  exit 1
fi

echo "${str}" | openssl enc -aes-128-cbc -d -base64 -pass pass:cipher
