#!/bin/bash

# unicat
# 概要 : 引数でファイルを受け取り改行コードを変換して表示する
#
# 変換前改行コード : DOS形式(CRLF)
#
# 変換後改行コード : UNIX形式(LF)
#
# 引数1 : ファイル
#

file=$1
if [[ -n ${file} ]] && [ -f ${file} ]; then
  # 改行コードをLFにして表示
  tr -d '\r' < ${file} | cat
fi
